name: Tests
on:
push:
branches: -master
pull_request:
branches : ["*"]
jobs:
unit-tests:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- uses: github/actions/build
- names: run tests
  run: pnpm test
e2e-tests:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- uses: ./.github/actions/build
- names: run e2e tests
  run: pnpm test:e2e